name: Report an Issue
description: Report an issue with the project
title: '[Issue] <title>'
projects: ['Kjur0/3']
body:
  - type: markdown
    attributes:
      value: |
        If you have found a bug or have a feature request, please use specialized templates for them. This template is for general issues that don't fit into those categories.
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue scope
      description: Please select the scope of issue you are reporting.
      options:
        - GitHub/git related (repo issues, etc.)
        - NPM related (package issues, etc.)
        - Community related (communication, moderation, etc.)
        - Documentation related (missing documentation, typos, etc.)
        - Dependency related (issues with dependencies, compatibility, etc.)
        - Performance related (performance issues, optimizations, etc.)
        - Other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Please provide a detailed description of the issue you are facing.
    validations:
      required: true
